// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJXbeQ8_WpR4EvrTdMI5aJmN-jrT8EWgc',
    appId: '1:941446881468:web:48291e55b1e99a0d3130b9',
    messagingSenderId: '941446881468',
    projectId: 'saeed-demo-proj',
    authDomain: 'saeed-demo-proj.firebaseapp.com',
    storageBucket: 'saeed-demo-proj.firebasestorage.app',
    measurementId: 'G-4Z7WHQWBMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLZQWCum4zbI3xe7968NrHKdoizIdPEv0',
    appId: '1:941446881468:android:985d5c8853a02f073130b9',
    messagingSenderId: '941446881468',
    projectId: 'saeed-demo-proj',
    storageBucket: 'saeed-demo-proj.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB158-tbqZeElXmtrpQiRbqUYunaDaM8RU',
    appId: '1:941446881468:ios:9a260096bdb042f93130b9',
    messagingSenderId: '941446881468',
    projectId: 'saeed-demo-proj',
    storageBucket: 'saeed-demo-proj.firebasestorage.app',
    iosBundleId: 'com.example.photoUploadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB158-tbqZeElXmtrpQiRbqUYunaDaM8RU',
    appId: '1:941446881468:ios:9a260096bdb042f93130b9',
    messagingSenderId: '941446881468',
    projectId: 'saeed-demo-proj',
    storageBucket: 'saeed-demo-proj.firebasestorage.app',
    iosBundleId: 'com.example.photoUploadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJXbeQ8_WpR4EvrTdMI5aJmN-jrT8EWgc',
    appId: '1:941446881468:web:ca49375c7b712ee53130b9',
    messagingSenderId: '941446881468',
    projectId: 'saeed-demo-proj',
    authDomain: 'saeed-demo-proj.firebaseapp.com',
    storageBucket: 'saeed-demo-proj.firebasestorage.app',
    measurementId: 'G-4E69S88ZJZ',
  );
}
